### ISSUE TITLE
ppr-ui: add resource limits to build config

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/ppr-deprecated#255]
The ppr-ui-inter-bc.yaml does not match what is in OpenShift. The one in OpenShift contains explicit resource limits, probably because the build was failing due to out of memory errors. The one in OpenShift contains:

```
  resources:
    limits:
      cpu: '2'
      memory: 3Gi
    requests:
      cpu: 500m
      memory: 2Gi
```

Also compare OpenShift vs what's in GitHub to make sure that there are no other important differences.

Update the resources in the bc in GitHub.
